---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: /src/k8s.io/helm

steps:
  - name: build
    pull: default
    image: golang:1.12.9
    commands:
      # Fix the certificate errors https://stackoverflow.com/questions/69420529/app-engine-deploy-failing-with-fatal-unable-to-access-https-gopkg-in-yaml-v
      - apt update && apt install ca-certificates libgnutls30 -y
      - ./.circleci/bootstrap.sh
      - make test-unit
      - make build-cross
      - mv ./_dist/linux-arm64/rancher-helm ./_dist/linux-arm64/rancher-helm-arm64
      - mv ./_dist/linux-arm64/rancher-tiller ./_dist/linux-arm64/rancher-tiller-arm64
      - mv ./_dist/linux-s390x/rancher-helm ./_dist/linux-s390x/rancher-helm-s390x
      - mv ./_dist/linux-s390x/rancher-tiller ./_dist/linux-s390x/rancher-tiller-s390x
      - mv ./_dist/darwin-amd64/rancher-helm ./_dist/darwin-amd64/rancher-helm-darwin-amd64
      - mv ./_dist/darwin-amd64/rancher-tiller ./_dist/darwin-amd64/rancher-tiller-darwin-amd64
    environment:
      PROJECT_NAME: '"kubernetes-helm"'
      TARGETS: linux/amd64 linux/arm64 linux/s390x darwin/amd64
      VERSION: ${DRONE_TAG}

  - name: publish-github-rc
    pull: default
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
      files:
        - "bin/*"
        - _dist/linux-amd64/*
        - _dist/linux-arm64/*
        -  dist/linux-s390x/*
        - _dist/darwin-amd64/*
      prerelease: true
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
      ref:
        - "refs/tags/*rc*"
        - refs/heads/rancher

  - name: github_binary_release
    pull: default
    image: plugins/github-release
    settings:
      checksum:
        - sha256
      files:
        - "bin/*"
        - _dist/linux-amd64/*
        - _dist/linux-arm64/*
        - _dist/linux-s390x/*
        - _dist/darwin-amd64/*
      api_key:
        from_secret: github_token
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
      ref:
        exclude:
          - "refs/tags/*rc*"
